
import React from 'react';
import { BookOpen, Calendar, CheckSquare, BarChart3, Bell, Settings, LogOut, User as UserIcon } from 'lucide-react';

export const COLORS = [
  '#3b82f6', // blue
  '#ef4444', // red
  '#10b981', // emerald
  '#f59e0b', // amber
  '#8b5cf6', // violet
  '#ec4899', // pink
  '#06b6d4', // cyan
];

export const PREDEFINED_AVATARS = [
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Buddy',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Caleb',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Dusty',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Eden',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Fiona',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=George',
];

// Mapping from Class Periods (Tiết) to Time slots based on the provided image
export const PERIOD_TIME_MAP: Record<number, { start: string, end: string }> = {
  1: { start: "07:00", end: "07:50" },
  2: { start: "07:55", end: "08:45" },
  3: { start: "08:50", end: "09:40" },
  4: { start: "09:50", end: "10:40" },
  5: { start: "10:45", end: "11:35" },
  6: { start: "12:30", end: "13:20" },
  7: { start: "13:25", end: "14:15" },
  8: { start: "14:20", end: "15:10" },
  9: { start: "15:20", end: "16:10" },
  10: { start: "16:15", end: "17:05" },
  11: { start: "17:30", end: "18:20" },
  12: { start: "18:25", end: "19:15" },
  13: { start: "19:20", end: "20:10" },
  14: { start: "20:15", end: "21:05" },
};

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    timetable: "Timetable",
    tasks: "Tasks",
    notes: "Notes",
    reminders: "Reminders",
    profile: "Profile",
    signOut: "Sign Out",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    language: "Language",
    classesToday: "Classes Today",
    activeTasks: "Active Tasks",
    completedTasks: "Completed Tasks",
    studyStreak: "Study Streak",
    studyEfficiency: "Study Efficiency",
    taskDistribution: "Task Distribution",
    upcomingClasses: "Upcoming Classes Today",
    viewAll: "View All",
    pendingAssignments: "Pending Assignments",
    manageTasks: "Manage Tasks",
    addClass: "Add Class",
    editClass: "Edit Class",
    day: "Day",
    week: "Week",
    month: "Month",
    subjectTitle: "Subject Title",
    code: "Code",
    instructor: "Instructor",
    type: "Type",
    startTime: "Start Time",
    endTime: "End Time",
    room: "Room / Platform",
    link: "Meeting Link",
    cancel: "Cancel",
    createEvent: "Create Event",
    saveChanges: "Save Changes",
    searchTasks: "Search assignments...",
    newTask: "New Task",
    editTask: "Edit Task",
    allStatus: "All Status",
    todo: "To Do",
    inProgress: "In Progress",
    completed: "Completed",
    urgent: "URGENT",
    save: "Save",
    newNote: "New Note",
    searchNotes: "Search notes...",
    notificationChannels: "Notification Channels",
    browserPush: "Browser Push",
    emailDigest: "Email Digest",
    upcomingAlerts: "Upcoming Alerts",
    full_name: "Full Name",
    major: "Major / Specialization",
    security: "Security & Account",
    changePassword: "Change Password",
    welcome: "Welcome Back",
    createAccount: "Create Account",
    signIn: "Sign In",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    signUp: "Sign Up",
    logIn: "Log In",
    regular: "Regular Study",
    online: "Online Study",
    exam: "Exam",
    eventNotes: "Class Notes",
    reminder: "Reminder",
    none: "None",
    minBefore: "mins before",
    hour: "hour",
    am: "AM",
    pm: "PM",
    description: "Description",
    deadline: "Deadline",
    priority: "Priority",
    status: "Status",
    low: "Low",
    medium: "Medium",
    high: "High",
    personal_info: "Personal Information",
    email_address: "Email Address",
    edit_profile_btn: "Edit Profile",
    task_title: "Task Title",
    task_title_placeholder: "Enter task title...",
    details_placeholder: "Enter additional details...",
    noTasksFound: "No tasks found.",
    studyJournal: "Study Journal",
    searchContent: "Search content...",
    untitled: "Untitled",
    clickToWrite: "Click to write...",
    selectSubjectPrompt: "Please select a subject to start taking notes.",
    chooseSubject: "Choose subject...",
    noRecords: "No records found.",
    studyHours: "Study Hours",
    noClassesToday: "No classes scheduled for today.",
    due: "Due",
    noUrgentAlerts: "No urgent alerts.",
    email: "Email",
    password: "Password",
    export: "Export",
    import: "Import",
    exportPDF: "Export PDF",
    exportExcel: "Export Excel",
    importCSV: "Import CSV",
    importImage: "Import from Image",
    importSuccess: "Import successful!",
    importError: "Import failed. Please check file format.",
    analyzingImage: "Analyzing image with AI...",
    selectAvatar: "Select Avatar",
    typeLabels: {
      REGULAR: "REG",
      ONLINE: "ONL",
      EXAM: "EXM"
    },
    labels: {
      subject: "Subj:",
      instructor: "Inst:",
      room: "Room:"
    }
  },
  vi: {
    dashboard: "Tổng quan",
    timetable: "Thời khóa biểu",
    tasks: "Nhiệm vụ",
    notes: "Ghi chú",
    reminders: "Nhắc nhở",
    profile: "Cá nhân",
    signOut: "Đăng xuất",
    darkMode: "Chế độ tối",
    lightMode: "Chế độ sáng",
    language: "Ngôn ngữ",
    classesToday: "Tiết học hôm nay",
    activeTasks: "Nhiệm vụ cần làm",
    completedTasks: "Đã hoàn thành",
    studyStreak: "Chuỗi học tập",
    studyEfficiency: "Hiệu suất học tập",
    taskDistribution: "Phân bổ nhiệm vụ",
    upcomingClasses: "Tiết học sắp tới",
    viewAll: "Xem tất cả",
    pendingAssignments: "Bài tập chờ xử lý",
    manageTasks: "Quản lý nhiệm vụ",
    addClass: "Thêm lịch học",
    editClass: "Sửa lịch học",
    day: "Ngày",
    week: "Tuần",
    month: "Tháng",
    subjectTitle: "Tên môn học",
    code: "Mã môn",
    instructor: "Giảng viên",
    type: "Loại hình",
    startTime: "Giờ bắt đầu",
    endTime: "Giờ kết thúc",
    room: "Phòng học / Nền tảng",
    link: "Link cuộc họp",
    cancel: "Hủy",
    createEvent: "Tạo lịch",
    saveChanges: "Lưu thay đổi",
    searchTasks: "Tìm kiếm bài tập...",
    newTask: "Nhiệm vụ mới",
    editTask: "Chỉnh sửa nhiệm vụ",
    allStatus: "Tất cả trạng thái",
    todo: "Cần làm",
    inProgress: "Đang làm",
    completed: "Hoàn thành",
    urgent: "KHẨN CẤP",
    save: "Lưu",
    newNote: "Ghi chú mới",
    searchNotes: "Tìm kiếm ghi chú...",
    notificationChannels: "Kênh thông báo",
    browserPush: "Thông báo trình duyệt",
    emailDigest: "Email tổng hợp",
    upcomingAlerts: "Cảnh báo sắp tới",
    full_name: "Họ và tên",
    major: "Chuyên ngành",
    security: "Bảo mật & Tài khoản",
    changePassword: "Đổi mật khẩu",
    welcome: "Chào mừng trở lại",
    createAccount: "Tạo tài khoản",
    signIn: "Đăng nhập",
    dontHaveAccount: "Chưa có tài khoản?",
    alreadyHaveAccount: "Đã có tài khoản?",
    signUp: "Đăng ký",
    logIn: "Đăng nhập",
    regular: "Học trên lớp",
    online: "Học trực tuyến",
    exam: "Lịch thi",
    eventNotes: "Ghi chú tiết học",
    reminder: "Nhắc nhở",
    none: "Không có",
    minBefore: "phút trước",
    hour: "giờ",
    am: "SA",
    pm: "CH",
    description: "Mô tả",
    deadline: "Hạn chót",
    priority: "Mức độ ưu tiên",
    status: "Trạng thái",
    low: "Thấp",
    medium: "Trung bình",
    high: "Cao",
    personal_info: "Thông tin cá nhân",
    email_address: "Địa chỉ Email",
    edit_profile_btn: "Sửa hồ sơ",
    task_title: "Tiêu đề nhiệm vụ",
    task_title_placeholder: "Nhập tiêu đề nhiệm vụ...",
    details_placeholder: "Nhập chi tiết nhiệm vụ...",
    noTasksFound: "Không tìm thấy nhiệm vụ nào.",
    studyJournal: "Nhật ký học tập",
    searchContent: "Tìm kiếm nội dung...",
    untitled: "Chưa đặt tên",
    clickToWrite: "Nhấn để viết...",
    selectSubjectPrompt: "Vui lòng chọn môn học để bắt đầu ghi chú.",
    chooseSubject: "Chọn môn học...",
    noRecords: "Chưa có bản ghi nào.",
    studyHours: "Giờ học",
    noClassesToday: "Không có tiết học nào trong hôm nay.",
    due: "Hạn",
    noUrgentAlerts: "Không có cảnh báo khẩn cấp.",
    email: "Email",
    password: "Mật khẩu",
    export: "Xuất file",
    import: "Nhập file",
    exportPDF: "Xuất PDF",
    exportExcel: "Xuất Excel",
    importCSV: "Nhập từ CSV",
    importImage: "Quét ảnh TKB",
    importSuccess: "Nhập dữ liệu thành công!",
    importError: "Lỗi nhập liệu hoặc không đọc được ảnh.",
    analyzingImage: "AI đang phân tích ảnh...",
    selectAvatar: "Chọn ảnh đại diện",
    typeLabels: {
      REGULAR: "LỚP",
      ONLINE: "WEB",
      EXAM: "THI"
    },
    labels: {
      subject: "Môn:",
      instructor: "GV:",
      room: "Phòng:"
    }
  }
};

export const NAV_ITEMS = [
  { id: 'dashboard', labelKey: 'dashboard', icon: <BarChart3 className="w-5 h-5" /> },
  { id: 'timetable', labelKey: 'timetable', icon: <Calendar className="w-5 h-5" /> },
  { id: 'tasks', labelKey: 'tasks', icon: <CheckSquare className="w-5 h-5" /> },
  { id: 'notes', labelKey: 'notes', icon: <BookOpen className="w-5 h-5" /> },
  { id: 'reminders', labelKey: 'reminders', icon: <Bell className="w-5 h-5" /> },
  { id: 'profile', labelKey: 'profile', icon: <UserIcon className="w-5 h-5" /> },
];

export const DAYS_EN = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
export const DAYS_VI = ['Chủ Nhật', 'Thứ Hai', 'Thứ Ba', 'Thứ Tư', 'Thứ Năm', 'Thứ Sáu', 'Thứ Bảy'];
export const SHORT_DAYS_EN = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
export const SHORT_DAYS_VI = ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'];

export const INITIAL_USER = {
  id: '1',
  email: 'student@uniflow.edu',
  fullName: 'Trung Hai',
  major: 'Công nghệ phần mềm',
  avatar: PREDEFINED_AVATARS[0]
};
